services:
  bot:
    container_name: "BOT_${NAME}"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/bot"
    volumes:
      - .:/usr/src/app/bot
    command: python3 -u bot.py
    restart: always
    env_file:
      - ".env"

    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

#  redis:
#    image: redis:6.2-alpine
#    container_name: redis_${POSTFIX}
#    restart: always
#    command: redis-server --port $REDIS_PORT --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
#    env_file:
#      - ".env"
#    networks:
#      - local_network
#    volumes:
#      - cache:/data
#
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "100k"
#        max-file: "10"

#  pg_database:
#    image: postgres:13-alpine
#    container_name: "postgres_${NAME}"
#    expose:
#      - 5432
#    restart: always
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    command: "postgres -c max_connections=150
#             -c shared_buffers=512MB -c effective_cache_size=1536MB
#             -c maintenance_work_mem=128MB -c checkpoint_completion_target=0.9 -c wal_buffers=16MB
#             -c default_statistics_target=100 -c random_page_cost=1.1 -c effective_io_concurrency=200
#             -c work_mem=3495kB -c min_wal_size=1GB -c max_wal_size=4GB -c max_worker_processes=2
#             -c max_parallel_workers_per_gather=1 -c max_parallel_workers=2 -c max_parallel_maintenance_workers=1"
#    env_file:
#      - ".env"
#
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "200k"
#        max-file: "10"

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: "pgadmin4_${NAME}"
#    restart: always
#    ports:
#      - "8888:80"
#    networks:
#      - tg_bot
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
#      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin
#
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "200k"
#        max-file: "10"

#volumes:
#  cache: { }
#  pgdata:
#  pgadmin-data:
